/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRadioRouteImport } from './routes/_app.radio'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppLabelsRouteImport } from './routes/_app.labels'
import { Route as AppHallOfFameRouteImport } from './routes/_app.hall-of-fame'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppBattlesRouteImport } from './routes/_app.battles'
import { Route as AppAvatarLabRouteImport } from './routes/_app.avatar-lab'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppLabelsIndexRouteImport } from './routes/_app.labels.index'
import { Route as AppArtistsIndexRouteImport } from './routes/_app.artists.index'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'
import { Route as ApiStudioGenerateRouteImport } from './routes/api/studio/generate'
import { Route as AppLabelsLabelIdRouteImport } from './routes/_app.labels.$labelId'
import { Route as AppArtistsArtistIdRouteImport } from './routes/_app.artists.$artistId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRadioRoute = AppRadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsRoute = AppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppHallOfFameRoute = AppHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppBattlesRoute = AppBattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => AppRoute,
} as any)
const AppAvatarLabRoute = AppAvatarLabRouteImport.update({
  id: '/avatar-lab',
  path: '/avatar-lab',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsIndexRoute = AppLabelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLabelsRoute,
} as any)
const AppArtistsIndexRoute = AppArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => AppRoute,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudioGenerateRoute = ApiStudioGenerateRouteImport.update({
  id: '/api/studio/generate',
  path: '/api/studio/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLabelsLabelIdRoute = AppLabelsLabelIdRouteImport.update({
  id: '/$labelId',
  path: '/$labelId',
  getParentRoute: () => AppLabelsRoute,
} as any)
const AppArtistsArtistIdRoute = AppArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/avatar-lab': typeof AppAvatarLabRoute
  '/battles': typeof AppBattlesRoute
  '/community': typeof AppCommunityRoute
  '/hall-of-fame': typeof AppHallOfFameRoute
  '/labels': typeof AppLabelsRouteWithChildren
  '/library': typeof AppLibraryRoute
  '/radio': typeof AppRadioRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRoute
  '/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/api/studio/generate': typeof ApiStudioGenerateRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/artists/': typeof AppArtistsIndexRoute
  '/labels/': typeof AppLabelsIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AppAnalyticsRoute
  '/avatar-lab': typeof AppAvatarLabRoute
  '/battles': typeof AppBattlesRoute
  '/community': typeof AppCommunityRoute
  '/hall-of-fame': typeof AppHallOfFameRoute
  '/library': typeof AppLibraryRoute
  '/radio': typeof AppRadioRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRoute
  '/': typeof AppIndexRoute
  '/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/api/studio/generate': typeof ApiStudioGenerateRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/artists': typeof AppArtistsIndexRoute
  '/labels': typeof AppLabelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/avatar-lab': typeof AppAvatarLabRoute
  '/_app/battles': typeof AppBattlesRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/hall-of-fame': typeof AppHallOfFameRoute
  '/_app/labels': typeof AppLabelsRouteWithChildren
  '/_app/library': typeof AppLibraryRoute
  '/_app/radio': typeof AppRadioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/': typeof AppIndexRoute
  '/_app/artists/$artistId': typeof AppArtistsArtistIdRoute
  '/_app/labels/$labelId': typeof AppLabelsLabelIdRoute
  '/api/studio/generate': typeof ApiStudioGenerateRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/_app/artists/': typeof AppArtistsIndexRoute
  '/_app/labels/': typeof AppLabelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/analytics'
    | '/avatar-lab'
    | '/battles'
    | '/community'
    | '/hall-of-fame'
    | '/labels'
    | '/library'
    | '/radio'
    | '/settings'
    | '/studio'
    | '/artists/$artistId'
    | '/labels/$labelId'
    | '/api/studio/generate'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/artists/'
    | '/labels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/analytics'
    | '/avatar-lab'
    | '/battles'
    | '/community'
    | '/hall-of-fame'
    | '/library'
    | '/radio'
    | '/settings'
    | '/studio'
    | '/'
    | '/artists/$artistId'
    | '/labels/$labelId'
    | '/api/studio/generate'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/artists'
    | '/labels'
  id:
    | '__root__'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/analytics'
    | '/_app/avatar-lab'
    | '/_app/battles'
    | '/_app/community'
    | '/_app/hall-of-fame'
    | '/_app/labels'
    | '/_app/library'
    | '/_app/radio'
    | '/_app/settings'
    | '/_app/studio'
    | '/_app/'
    | '/_app/artists/$artistId'
    | '/_app/labels/$labelId'
    | '/api/studio/generate'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/_app/artists/'
    | '/_app/labels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiStudioGenerateRoute: typeof ApiStudioGenerateRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/radio': {
      id: '/_app/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof AppRadioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels': {
      id: '/_app/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AppLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hall-of-fame': {
      id: '/_app/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof AppHallOfFameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/battles': {
      id: '/_app/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof AppBattlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avatar-lab': {
      id: '/_app/avatar-lab'
      path: '/avatar-lab'
      fullPath: '/avatar-lab'
      preLoaderRoute: typeof AppAvatarLabRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels/': {
      id: '/_app/labels/'
      path: '/'
      fullPath: '/labels/'
      preLoaderRoute: typeof AppLabelsIndexRouteImport
      parentRoute: typeof AppLabelsRoute
    }
    '/_app/artists/': {
      id: '/_app/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof AppArtistsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio/generate': {
      id: '/api/studio/generate'
      path: '/api/studio/generate'
      fullPath: '/api/studio/generate'
      preLoaderRoute: typeof ApiStudioGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/labels/$labelId': {
      id: '/_app/labels/$labelId'
      path: '/$labelId'
      fullPath: '/labels/$labelId'
      preLoaderRoute: typeof AppLabelsLabelIdRouteImport
      parentRoute: typeof AppLabelsRoute
    }
    '/_app/artists/$artistId': {
      id: '/_app/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof AppArtistsArtistIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppLabelsRouteChildren {
  AppLabelsLabelIdRoute: typeof AppLabelsLabelIdRoute
  AppLabelsIndexRoute: typeof AppLabelsIndexRoute
}

const AppLabelsRouteChildren: AppLabelsRouteChildren = {
  AppLabelsLabelIdRoute: AppLabelsLabelIdRoute,
  AppLabelsIndexRoute: AppLabelsIndexRoute,
}

const AppLabelsRouteWithChildren = AppLabelsRoute._addFileChildren(
  AppLabelsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAvatarLabRoute: typeof AppAvatarLabRoute
  AppBattlesRoute: typeof AppBattlesRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppHallOfFameRoute: typeof AppHallOfFameRoute
  AppLabelsRoute: typeof AppLabelsRouteWithChildren
  AppLibraryRoute: typeof AppLibraryRoute
  AppRadioRoute: typeof AppRadioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudioRoute: typeof AppStudioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArtistsArtistIdRoute: typeof AppArtistsArtistIdRoute
  AppArtistsIndexRoute: typeof AppArtistsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAvatarLabRoute: AppAvatarLabRoute,
  AppBattlesRoute: AppBattlesRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppHallOfFameRoute: AppHallOfFameRoute,
  AppLabelsRoute: AppLabelsRouteWithChildren,
  AppLibraryRoute: AppLibraryRoute,
  AppRadioRoute: AppRadioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudioRoute: AppStudioRoute,
  AppIndexRoute: AppIndexRoute,
  AppArtistsArtistIdRoute: AppArtistsArtistIdRoute,
  AppArtistsIndexRoute: AppArtistsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiStudioGenerateRoute: ApiStudioGenerateRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
