/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as AppAvatarLabRouteImport } from './routes/_app.avatar-lab'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppAvatarLabRoute = AppAvatarLabRouteImport.update({
  id: '/avatar-lab',
  path: '/avatar-lab',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/avatar-lab': typeof AppAvatarLabRoute
  '/studio': typeof AppStudioRoute
}
export interface FileRoutesByTo {
  '/avatar-lab': typeof AppAvatarLabRoute
  '/studio': typeof AppStudioRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/avatar-lab': typeof AppAvatarLabRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avatar-lab' | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to: '/avatar-lab' | '/studio' | '/'
  id: '__root__' | '/_app' | '/_app/avatar-lab' | '/_app/studio' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avatar-lab': {
      id: '/_app/avatar-lab'
      path: '/avatar-lab'
      fullPath: '/avatar-lab'
      preLoaderRoute: typeof AppAvatarLabRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAvatarLabRoute: typeof AppAvatarLabRoute
  AppStudioRoute: typeof AppStudioRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvatarLabRoute: AppAvatarLabRoute,
  AppStudioRoute: AppStudioRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
